// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKIJI0qHRsb5FgqbGRBqEVayllT7rbj-A',
    appId: '1:285063561267:web:a608edcd9ace969860e346',
    messagingSenderId: '285063561267',
    projectId: 'recipeapp-ac18d',
    authDomain: 'recipeapp-ac18d.firebaseapp.com',
    storageBucket: 'recipeapp-ac18d.firebasestorage.app',
    measurementId: 'G-K183H5P5WS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR9_BNEUiRaOE-NatbpXJJO30Oyme29T4',
    appId: '1:285063561267:android:5444a35be65b68e360e346',
    messagingSenderId: '285063561267',
    projectId: 'recipeapp-ac18d',
    storageBucket: 'recipeapp-ac18d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5HmheMnuY2U5tPT-4O9Sh1VVv1J3YMsQ',
    appId: '1:285063561267:ios:88b23bb34faff3c060e346',
    messagingSenderId: '285063561267',
    projectId: 'recipeapp-ac18d',
    storageBucket: 'recipeapp-ac18d.firebasestorage.app',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5HmheMnuY2U5tPT-4O9Sh1VVv1J3YMsQ',
    appId: '1:285063561267:ios:88b23bb34faff3c060e346',
    messagingSenderId: '285063561267',
    projectId: 'recipeapp-ac18d',
    storageBucket: 'recipeapp-ac18d.firebasestorage.app',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKIJI0qHRsb5FgqbGRBqEVayllT7rbj-A',
    appId: '1:285063561267:web:7cae7f473c2e27fc60e346',
    messagingSenderId: '285063561267',
    projectId: 'recipeapp-ac18d',
    authDomain: 'recipeapp-ac18d.firebaseapp.com',
    storageBucket: 'recipeapp-ac18d.firebasestorage.app',
    measurementId: 'G-4BPDPVL7DB',
  );
}